// <auto-generated />
using System;
using LifePlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifePlanner.Api.Migrations
{
    [DbContext(typeof(LifePlannerDbContext))]
    partial class LifePlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LifePlanner.Api.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("CategoryId")
                        ;

                    b.Property<string>("Color")
                        ;

                    b.Property<string>("Description")
                        ;

                    b.Property<string>("IntegrationExternalId")
                        ;

                    b.Property<string>("IntegrationSource")
                        ;

                    b.Property<bool>("IsChecklist")
                        ;

                    b.Property<bool>("IsStickyNote")
                        ;

                    b.Property<int>("Order")
                        ;

                    b.Property<DateTime?>("ScheduledDate")
                        ;

                    b.Property<string>("Title")
                        .IsRequired()
                        ;

                    b.Property<int>("UserId")
                        ;

                    b.Property<double?>("WhiteboardX")
                        ;

                    b.Property<double?>("WhiteboardY")
                        ;

                    b.Property<int?>("WorkspaceId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Color")
                        .IsRequired()
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.Property<int>("UserId")
                        ;

                    b.Property<int?>("WorkspaceId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AdminNotes")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("Description")
                        .IsRequired()
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        ;

                    b.Property<string>("Title")
                        .IsRequired()
                        ;

                    b.Property<string>("Type")
                        .IsRequired()
                        ;

                    b.Property<int?>("UserId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("CardId")
                        ;

                    b.Property<string>("IntegrationExternalId")
                        ;

                    b.Property<bool>("IsCompleted")
                        ;

                    b.Property<string>("Position")
                        ;

                    b.Property<string>("Text")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.ScheduledInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("CategoryId")
                        ;

                    b.Property<DateTime>("Date")
                        ;

                    b.Property<string>("Description")
                        ;

                    b.Property<DateTime?>("EndTime")
                        ;

                    b.Property<string>("GoogleEventId")
                        ;

                    b.Property<bool>("IsCompleted")
                        ;

                    b.Property<bool>("IsConfirmed")
                        ;

                    b.Property<int?>("ListItemId")
                        ;

                    b.Property<DateTime?>("StartTime")
                        ;

                    b.Property<string>("Title")
                        ;

                    b.Property<string>("Type")
                        ;

                    b.Property<int>("UserId")
                        ;

                    b.Property<int?>("WorkspaceId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ListItemId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ScheduledInstances");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Email")
                        .IsRequired()
                        ;

                    b.Property<string>("GoogleAccessToken")
                        ;

                    b.Property<string>("GoogleAuthId")
                        ;

                    b.Property<string>("GoogleRefreshToken")
                        ;

                    b.Property<bool>("GoogleTasksConnected")
                        ;

                    b.Property<DateTime?>("GoogleTokenExpiration")
                        ;

                    b.Property<bool>("IsAdmin")
                        ;

                    b.Property<string>("MicrosoftAccessToken")
                        ;

                    b.Property<string>("MicrosoftRefreshToken")
                        ;

                    b.Property<bool>("MicrosoftTodoConnected")
                        ;

                    b.Property<DateTime?>("MicrosoftTokenExpiration")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("InviteToken")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.WorkspaceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Role")
                        .IsRequired()
                        ;

                    b.Property<int>("UserId")
                        ;

                    b.Property<int>("WorkspaceId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkspaceUsers");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Card", b =>
                {
                    b.HasOne("LifePlanner.Api.Models.Category", "Category")
                        .WithMany("Cards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifePlanner.Api.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifePlanner.Api.Models.Workspace", "Workspace")
                        .WithMany("Cards")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Category", b =>
                {
                    b.HasOne("LifePlanner.Api.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifePlanner.Api.Models.Workspace", "Workspace")
                        .WithMany("Categories")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Feedback", b =>
                {
                    b.HasOne("LifePlanner.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.ListItem", b =>
                {
                    b.HasOne("LifePlanner.Api.Models.Card", "Card")
                        .WithMany("ListItems")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.ScheduledInstance", b =>
                {
                    b.HasOne("LifePlanner.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("LifePlanner.Api.Models.ListItem", "ListItem")
                        .WithMany("ScheduledInstances")
                        .HasForeignKey("ListItemId");

                    b.HasOne("LifePlanner.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifePlanner.Api.Models.Workspace", "Workspace")
                        .WithMany("ScheduledInstances")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("ListItem");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.WorkspaceUser", b =>
                {
                    b.HasOne("LifePlanner.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifePlanner.Api.Models.Workspace", "Workspace")
                        .WithMany("WorkspaceUsers")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Card", b =>
                {
                    b.Navigation("ListItems");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Category", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.ListItem", b =>
                {
                    b.Navigation("ScheduledInstances");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("LifePlanner.Api.Models.Workspace", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Categories");

                    b.Navigation("ScheduledInstances");

                    b.Navigation("WorkspaceUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
